name: unit-test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Hardhat unit test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Environment
      uses: actions/setup-node@v3
      working-directory: contract
    - name: Test
      uses: ambersun1234/hardhat-test-action@v1
      working-directory: contract
      with:
        network: hardhat
